spring:
  application:
    name: creditassessor
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: admin
    password: admin
    
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:dcIO$3^0S6hM@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    card-issue: card-issue
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
logging:
  file:
    name: ./logs/log-file.log